version: '3.7'
services:
  database:
    image: 'mongo'
    container_name: 'tesladb'
    volumes:
      - ~/mongodb/data/tesladb:/data/db
    expose:
      - '27017'
    command: mongod --auth

  server:
    build: .
    container_name: 'teslapp'
    depends_on:
      - database
    ports:
      - '7057:3000'
    expose:
      - '7057'
    environment:
      NODE_ENV: 'development'
      PORT: 3000

