import {IChargeSession} from './ChargeSession';

export interface IChargeState {
  _id: string;
  id_s: string,
  vehicle_id: number,
  battery_heater_on: boolean,
  battery_level: number,
  battery_range: number,
  charge_current_request: number,
  charge_energy_added: number,
  charge_miles_added_ideal: number,
  charge_miles_added_rated: number,
  charge_port_door_open: boolean,
  charge_port_latch: string,
  charge_rate: number,
  charger_actual_current: number,
  charger_power: number,
  charger_voltage: number,
  charging_state: string,
  est_battery_range: number,
  ideal_battery_range: number,
  time_to_full_charge: number,
  timestamp: number,
  driver_temp_setting: number,
  fan_status: number,
  inside_temp: number,
  is_auto_conditioning_on: boolean,
  is_climate_on: boolean,
  is_front_defroster_on: boolean,
  is_preconditioning: boolean,
  is_rear_defroster_on: boolean,
  outside_temp: number,
  passenger_temp_setting: number,
  seat_heater_left: number,
  seat_heater_rear_center: number,
  seat_heater_rear_left: number,
  seat_heater_rear_right: number,
  seat_heater_right: number,
  side_mirror_heaters: boolean,
  smart_preconditioning: boolean,
  is_user_present: boolean,

  chargeSession?: IChargeSession
}
